cart/urls.py
from django.urls import path

from cart import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path("order/", views.OrderView.as_view(), name="order"),
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", "main")),
    path("account/", include("account.urls", "account")),
    path("cart/", include("cart.urls", "cart")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.extend(
        [
            path("__debug__/", include("debug_toolbar.urls")),
        ]
    )

main/urls.py
from django.conf.urls.static import static
from django.urls import path

from core import settings
from . import views

app_name = "main"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("s/<str:sex>/", views.SexView.as_view(), name="sex"),
    path(
        "s/<str:sex>/main-category/<slug:main_category_slug>/",
        views.MainCategoryView.as_view(),
        name="main-category",
    ),
    path(
        "s/<str:sex>/category/<slug:category_slug>/",
        views.CategoryView.as_view(),
        name="category",
    ),
    path(
        "product-detail/<int:pk>/",
        views.ProductDetailView.as_view(),
        name="product-detail",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.contrib.auth import get_user_model
from django.db import models
from phone_field import PhoneField

from main.models import BaseModel, Product, ProductWarehouseInfo

User = get_user_model()


class Order(BaseModel):
    class Status(models.TextChoices):
        IN_PROCESS = "IN_PROCESS"
        WAITING = "WAITING"
        DONE = "DONE"

    def __str__(self):
        return f"{self.user}: {self.status}"

    user = models.ForeignKey(User, models.DO_NOTHING, related_name="orders")
    contact_email = models.EmailField(null=False)
    contact_phone = PhoneField(null=False)
    contact_place = models.CharField(max_length=150, null=False, blank=False)
    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.IN_PROCESS
    )
    products_warehouse_info = models.ManyToManyField(
        ProductWarehouseInfo,
        related_name="orders",
    )

cart/views.py
from typing import Optional

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import ListView, TemplateView

from cart.exceptions import CartDoesNotExist
from cart.services import CartService
from cart.services.order import OrderService
from core.services import PageViewMixin
from main.exception import ProductNotAvailableException
from main.services import ProductWarehouseInfoService


@method_decorator(login_required, "dispatch")
class CartView(PageViewMixin, ListView):
    template_name = "cart/cart.html"
    context_object_name = "product_infos"
    page_title = "Корзина"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.products_sum: Optional[dict] = None
        self.cart_service = CartService()

    def get_queryset(self):
        cart, _ = self.cart_service.get_or_create_cart(self.request)
        product_infos = self.cart_service.get_all_product_infos_by_cart(cart)
        self.products_sum = self.cart_service.get_products_price_sum(cart)

        return product_infos

    def get_context_data(self, **kwargs):
        return (
            super().get_context_data(**kwargs)
            | self.get_page_context_data()
            | {"products_sum": self.products_sum}
        )


@method_decorator(login_required, "dispatch")
@method_decorator(transaction.atomic, "post")
class OrderView(PageViewMixin, TemplateView):
    template_name = "cart/buy.html"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.order_service = OrderService()
        self.cart_service = CartService()
        self.product_warehouse_service = ProductWarehouseInfoService()

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs) | self.get_page_context_data()

    def post(self, request):
        email = request.POST.get("email") or ""
        phone = request.POST.get("phone") or ""
        place = request.POST.get("place") or ""
        if "" in [email, phone, place]:
            return redirect("cart:cart")
        try:
            order = self.order_service.create_order_by_cart(
                request, self.cart_service.get_cart(request), email, phone, place
            )
        except CartDoesNotExist:
            return redirect("main:index")
        except ProductNotAvailableException:
            return redirect("cart:cart")

        return self.render_to_response(
            self.get_context_data() | {"order": order},
        )

cart/templates/cart/buy.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'main/css/message.css' %}">
    <link rel="stylesheet" href="{% static 'cart/css/order.css' %}">
{% endblock %}

{% block body %}
    {% if order %}
        <div class="message-container">
            <div class="message-item">
                <div class="message-item-title">
                    Спасибо за оформление заказа! Ваш заказ:
                </div>
            </div>
            <div class="message-item">
                <div class="message-item__text">
                    Адрес доставки: {{ order.contact_place }}
                </div>
            </div>
            <div class="message-item">
                <div class="message-item__text">
                    Телефон: {{ order.contact_phone }}
                </div>
            </div>
            <div class="message-item">
                <div class="message-item__text">
                    Email: {{ order.contact_email }}
                </div>
            </div>
            {% for product_warehouse_info in order.products_warehouse_info.all %}
                <div class="message-item">
                    <div class="order-product">
                        <div class="order-product__image">
                            <div class="order-product-img">
                                <img src="{{ product_warehouse_info.product.image.url }}" alt="">
                            </div>
                        </div>
                        <div class="order-product-info">
                            <div class="order-product__title">
                                <p>{{ product_warehouse_info.product.title }}</p>
                            </div>
                            <div class="order-product__text">
                                <p>Размер: {{ product_warehouse_info.product_size }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    {% else %}
        <div class="message-container">
            <div class="message-item">
                <div class="message-item-title">
                    Вы сейчас не оформляете заказ
                </div>
            </div>
            <div class="message-item">
                <div class="message-item__text">
                    Пожалуйста, переходите на другую страницу
                </div>
            </div>
            <div class="message-item">
                <a href="{% url 'main:index' %}">
                    <button class="btn btn-dark">На главную</button>
                </a>
            </div>
        </div>
    {% endif %}
{% endblock %}

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static '/cart/css/cart.css' %}">
{% endblock %}

{% block js_register %}
    <script src="{% static '/cart/js/' %}"></script>
{% endblock %}

{% block body %}
    <div class="cart-container">
        <div class="cart-product-container">
            {% for product_info in product_infos %}
                <div class="cart-product" style="background-color: #fff;border-radius: 8px;box-shadow: 0 20px 20px rgb(48 52 59 / 7%);">
                    <input type="hidden" name="product_id" value="{{ product_info.product.id }}">
                    <img src="{{ product_info.product.image.url }}" class="cart-product-image" style="padding: 10px">
                    <div class="cart-product-description">
                        <div class="cart-product-description__title">
                            {{ product_info.product.title }}
                        </div>
                        <div class="cart-product-description__size">
                            Размер: {{ product_info.product_size }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="cart-aggregated-info" style="background-color: #fff;">
            <form method="post" action="{% url 'cart:order' %}" class="cart-user-info-form">
                {% csrf_token %}
                <div class="form-title" style="margin:10px 0">
                    Введите свои данные
                </div>
                <div class="field">
                    <label for="cart-form-email" class="field__label" style="padding-left:3px; margin-bottom: 2px">Email</label>
                    <input id="cart-form-email" required type="text" class="field__input" name="email"
                           value="{{ user.email }}">
                </div>
                <div class="field">
                    <label for="cart-form-phone" class="field__label" style="padding-left:3px;margin-bottom: 2px">Телефон</label>
                    <input id="cart-form-phone" required type="text" name="phone" class="field__input">
                </div>
                <div class="field">
                    <label for="cart-form-place" class="field__label" style="padding-left:3px;margin-bottom: 2px">Место доставки</label>
                    <input id="cart-form-place" required type="text" name="place" class="field__input">
                </div>
                <button id="submit-cart-order" class="btn btn-dark">
                    Подтвердить
                </button>
            </form>
        </div>
    </div>
{% endblock %}