account/urls.py
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path("signup/", views.AccountCreationView.as_view(), name="signup"),
    path("login/", views.AccountLoginView.as_view(), name="login"),
    path("logout/", views.AccountLogoutView.as_view(), name="logout"),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path("order/", views.OrderView.as_view(), name="order"),
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", "main")),
    path("account/", include("account.urls", "account")),
    path("cart/", include("cart.urls", "cart")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.extend(
        [
            path("__debug__/", include("debug_toolbar.urls")),
        ]
    )

main/urls.py
from django.conf.urls.static import static
from django.urls import path

from core import settings
from . import views

app_name = "main"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("s/<str:sex>/", views.SexView.as_view(), name="sex"),
    path(
        "s/<str:sex>/main-category/<slug:main_category_slug>/",
        views.MainCategoryView.as_view(),
        name="main-category",
    ),
    path(
        "s/<str:sex>/category/<slug:category_slug>/",
        views.CategoryView.as_view(),
        name="category",
    ),
    path(
        "product-detail/<int:pk>/",
        views.ProductDetailView.as_view(),
        name="product-detail",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_inc/begin.html
{% load static %}

<div class="begin">
    <img class="begin__img" src="{% static 'main/img/main_back.jpg' %}" alt="main_back">
    <div class="begin__wrapper">

        <div class="slogan__wrapper">
            <div class="begin__slogan">Think Different</div>
        </div>

        <div class="ul__wrapper">
            <ul class="begin__ul">
                <li class="begin__li"><a href="#">новинки</a></li>
                <li class="begin__li"><a href="#">одежда</a></li>
                <li class="begin__li"><a href="#">обувь</a></li>
                <li class="begin__li"><a href="#">аксессуары</a></li>
                <li class="begin__li"><a href="#">спорт</a></li>
            </ul>
        </div>

        <div class="input__wrapper">
            <input class="begin__search__input" type="text" placeholder="Поиск...">
            <img class="begin__search__icon" src="{% static 'main/icons/search.svg' %}" alt="">
        </div>
    </div>
</div>

templates/_inc/footer.html
<footer>
 <div class="container-footer">
   <div class="content">
     <div class="text">
      Ⓒ Django Shop
     </div>
     <div class="text">
      django-shop@gmail.com
     </div>
   </div>
 </div>
 <style>
  body {
   min-height: 100vh;
   margin: 0;
   display: flex;
   flex-direction: column;
  }
  footer {
   margin-top: auto;
   bottom: 0;
   background-color: #CED3CA;
  }
  .container-footer {
   width: 1140px;
   margin: 0 auto;
   padding: 30px 0;
  }
  .content {
   display: flex;
   justify-content: space-between;
   flex-direction: row;
  }
 </style>
</footer>

templates/_inc/genderChoice.html
{% load static %}

<div class="genderChoice">
    <div class="gender__man">
        <img class="gender__img" src="{% static 'main/img/man.jpg' %}" alt="">
        <div class="gender__descr">мужчины</div>
    </div>
    <div class="gender__woman">
        <img class="gender__img" src="{% static 'main/img/woman.jpg' %}" alt="">
        <div class="gender__descr">женщины</div>
    </div>
    <div class="gender__children">
        <img class="gender__img" src="{% static 'main/img/children.jpg' %}" alt="">
        <div class="gender__descr">дети</div>
    </div>
</div>

templates/_inc/header.html
{% load static %}

<header>
    <div class="header__section" style="padding-left: 30px">
        <div class="header__item">
            <a class="logo-icon" href="{% url 'main:index' %}">
                <img class="logo-icon" src="{% static '/main/icon/django.svg' %}"/>
            </a>
        </div>
        <a class="header__item header__item-text" href="{% url 'main:sex' 'man' %}">Мужская</a>
        <a class="header__item header__item-text" href="{% url 'main:sex' 'woman' %}">Женская</a>
    </div>
    {% if user.is_staff %}
        <div class="header__section">
            <a class="header__item header__item-text" href="/admin/">Войти в админку</a>
        </div>
    {% endif %}
    <div class="header__section" style="padding-right: 30px">
        {% if user.is_authenticated %}
            <a href="{% url 'cart:cart' %}">
                <img class="cart-icon" src="{% static '/main/icon/binnew.svg' %}"/>
            </a>
            <p class="header__item header__item-text">{{ request.user.email }}</p>
            <a href="{% url 'account:logout' %}" class="header__item header__item-text">Выйти</a>
        {% else %}
            <nav class="navbar navbar-expand-lg navbar-dark">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: #fff;">
                                    <img src="{% static '/main/icon/profile.svg' %}"/>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li><a class="header__item header__item-text" href="{% url 'account:login' %}">Вход</a></li>
                                    <li><a class="header__item header__item-text" href="{% url 'account:signup' %}">Регистрация</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="header__item">
                <a href="{% url 'cart:cart' %}" class="cart-icon">
                    <img src="{% static '/main/icon/binnew.svg' %}"/>
                </a>
            </div>
        {% endif %}
    </div>
</header>

templates/_inc/section1.html
<section class="content">
    
</section>